export const PRENDAS_DATA = [
  {
    id: 1,
    tipo: 'Buzo',
    nombre: 'Buzo Kote',
    descripcion:
      'Este buzo tiene tela esponjosa y es perfecto para mantenerte abrigado en los días fríos.',
    genero:'Mujer',
    imgUrl: ['../../assets/Images/Buzos/DISTRESSED CREWNECK GASTHETICA FRONT - .png','../../assets/Images/Buzos/DISTRESSED CREWNECK GASTHETICA BACK - .png','../../assets/Images/Buzos/DISTRESSED CREWNECK GASTHETICA FRONT - .png','../../assets/Images/Buzos/DISTRESSED CREWNECK GASTHETICA BACK - .png'],
    cuidados: 'Lavar a mano con agua fría.',
    talles: ['S', 'M', 'L', 'XL'],
    precio: 50000,
    stock: 'stock',
    destacada: true,
  },
  {
    id: 2,
    tipo: 'Pantalon',
    nombre: 'Fleece Sweetpants',
    descripcion:
      'Este pantalón vaquero combina estilo y durabilidad, ideal para un look moderno y casual.',
      genero:'Mujer',
      imgUrl: ['../../assets/Images/Pantalones/FLEECE SWEATPANTS GASTHETICA FRONT - .png','../../assets/Images/Pantalones/FLEECE SWEATPANTS GASTHETICA BACK - .png','../../assets/Images/Pantalones/FLEECE SWEATPANTS GASTHETICA FRONT - .png','../../assets/Images/Pantalones/FLEECE SWEATPANTS GASTHETICA BACK - .png'],
    cuidados: 'Lavado en seco.',
    talles: ['S', 'M', 'L'],
    precio: 30000,
    stock: 'stock',
    destacada: false,
  },
  {
    id: 3,
    tipo: 'Pantalon',
    nombre: 'Pantalón SweatPant',
    descripcion:
      'Un pantalón deportivo diseñado para brindarte libertad de movimiento y comodidad durante tus actividades físicas.',
      genero:'Mujer',
      imgUrl: ['../../assets/Images/Pantalones/SWEATPANTS GASTHETICA FRONT - .png','../../assets/Images/Pantalones/SWEATPANTS GASTHETICA BACK - .png','../../assets/Images/Pantalones/SWEATPANTS GASTHETICA FRONT - .png','../../assets/Images/Pantalones/SWEATPANTS GASTHETICA BACK - .png'],
    cuidados: 'Lavar a máquina en ciclo suave.',
    talles: ['S', 'M', 'L', 'XL'],
    precio: 35000,
    stock: 'sin stock',
    destacada: true,
  },

  {
    id: 4,
    tipo: 'Remera',
    nombre: 'Remera Estampada',
    descripcion:
      'Una remera cómoda y versátil con un estampado único que te hará destacar.',
      genero:'Mujer',
      imgUrl: ['../../assets/Images/Remeras/OVERSIZED TEE WASHED GASTHETICA FRONT - .png','../../assets/Images/Remeras/OVERSIZED TEE WASHED GASTHETICA BACK - .png','../../assets/Images/Remeras/OVERSIZED TEE WASHED GASTHETICA FRONT - .png','../../assets/Images/Remeras/OVERSIZED TEE WASHED GASTHETICA BACK - .png'],
    cuidados: 'Lavar a máquina en ciclo suave.',
    talles: ['S', 'M', 'L', 'XL'],
    precio: 20500,
    stock: 'stock',
    destacada: true,
  },
  {
    id: 5,
    tipo: 'Buzo',
    nombre: 'Buzo Classic',
    descripcion:
      'El buzo clásico que nunca pasa de moda, confeccionado con materiales de alta calidad para brindarte comodidad y estilo.',
      genero:'Hombre',
      imgUrl: ['../../assets/Images/Buzos/BOXY HOODIE GASTHETICA FRONT - .png','../../assets/Images/Buzos/BOXY HOODIE GASTHETICA BACK - .png','../../assets/Images/Buzos/BOXY HOODIE GASTHETICA FRONT - .png','../../assets/Images/Buzos/BOXY HOODIE GASTHETICA BACK - .png'],
    cuidados: 'Lavar en agua fría con colores similares.',
    talles: ['S', 'M', 'L', 'XL'],
    precio: 40500,
    stock: 'stock',
    destacada: true,
  },
  {
    id: 6,
    tipo: 'Pantalon',
    nombre: 'Jean Anark',
    descripcion:
      'Completa tu outfit con este elegante collar que resaltará tu estilo y personalidad.',
      genero:'Mujer',
      imgUrl: ['../../assets/Images/Pantalones/JEANS GASTHETICA FRONT - .png','../../assets/Images/Pantalones/JEANS GASTHETICA BACK - .png','../../assets/Images/Pantalones/JEANS GASTHETICA FRONT - .png','../../assets/Images/Pantalones/JEANS GASTHETICA BACK - .png'],
    cuidados: 'Evitar el contacto con perfumes y líquidos.',
    talles: ['Único'],
    precio: 10500,
    stock: 'stock',
    destacada: false,
  },
  {
    id: 7,
    tipo: 'Accesorio',
    nombre: 'Sombrero Vintage',
    descripcion:
      'Completa tu look retro con este sombrero vintage que te transportará a otra época.',
      genero:'Mujer',
      imgUrl: ['../../assets/Images/Accesorios/gorra2.jpg'],
    cuidados: 'Mantener alejado de la humedad.',
    talles: ['Único'],
    precio: 20000,
    stock: 'stock',
    destacada: false,
  },
  {
    id: 8,
    tipo: 'Remera',
    nombre: 'Remera Básica',
    descripcion:
      'Una remera básica y cómoda que combina con cualquier estilo y ocasión.',
      genero:'Unisex',
      imgUrl: ['../../assets/Images/Remeras/REGULAR TEE GASTHETICA FRONT - .png','../../assets/Images/Remeras/REGULAR TEE GASTHETICA BACK - .png','../../assets/Images/Remeras/DETAIL REGULAR TEE - .png','../../assets/Images/Remeras/REGULAR TEE GASTHETICA BACK - .png'],
    cuidados: 'Lavar a máquina en agua fría.',
    talles: ['S', 'M', 'L', 'XL'],
    precio: 20000,
    stock: 'sin stock',
    destacada: true,
  },
  {
    id: 9,
    tipo: 'Buzo',
    nombre: 'Buzo Casual',
    descripcion:
      'Un buzo casual perfecto para relajarte los fines de semana, confeccionado con suave algodón.',
      genero:'Unisex',
      imgUrl: ['../../assets/Images/Buzos/HEAVY CREWNECK GASTHETICA FRONT - .png','../../assets/Images/Buzos/HEAVY CREWNECK GASTHETICA BACK - .png','../../assets/Images/Buzos/HEAVY CREWNECK GASTHETICA FRONT - .png','../../assets/Images/Buzos/HEAVY CREWNECK GASTHETICA BACK - .png'],
    cuidados: 'Lavar a mano con agua fría y secar al aire.',
    talles: ['S', 'M', 'L'],
    precio: 40000,
    stock: 'stock',
    destacada: true,
  },
  {
    id: 10,
    tipo: 'Pantalon',
    nombre: 'Pantalón Cargo',
    descripcion:
      'Un pantalón de vestir elegante y sofisticado para ocasiones formales, con un corte moderno.',
      genero:'Mujer',
      imgUrl: ['../../assets/Images/Pantalones/CARGO PANTS GASTHETICA FRONT - .png','../../assets/Images/Pantalones/CARGO PANTS GASTHETICA BACK - .png','../../assets/Images/Pantalones/CARGO PANTS GASTHETICA FRONT - .png','../../assets/Images/Pantalones/CARGO PANTS GASTHETICA BACK - .png'],
    cuidados: 'Lavado en seco.',
    talles: ['S', 'M', 'L', 'XL'],
    precio: 50000,
    stock: 'sin stock',
    destacada: true,
  },
  {
    id: 11,
    tipo: 'Remera',
    nombre: 'Boxy Tee',
    descripcion:
      'Una cálida bufanda de lana para mantenerte abrigado durante los días fríos de invierno.',
      genero:'Unisex',
      imgUrl: ['../../assets/Images/Remeras/BOXY TEE GASTHETICA (VINTAGE) FRONT - .png','../../assets/Images/Remeras/BOXY TEE GASTHETICA (VINTAGE) BACK - .png','../../assets/Images/Remeras/BOXY TEE GASTHETICA (VINTAGE) FRONT - .png','../../assets/Images/Remeras/BOXY TEE GASTHETICA (VINTAGE) BACK - .png'],
    cuidados: 'Lavar a mano con detergente suave y secar al aire.',
    talles: ['Único'],
    precio: 15000,
    stock: 'stock',
    destacada: false,
  },
  {
    id: 12,
    tipo: 'Buzo',
    nombre: 'Hoodie Crop',
    descripcion:
      'Un buzo con un estampado original y llamativo que refleja tu personalidad única.',
      genero:'Hombre',
      imgUrl: ['../../assets/Images/Buzos/HOODIE CROP GASTHETICA (EXPERIMENTAL) FRONT - .png','../../assets/Images/Buzos/HOODIE CROP GASTHETICA (EXPERIMENTAL) BACK - .png','../../assets/Images/Buzos/HOODIE CROP GASTHETICA (EXPERIMENTAL) FRONT - .png','../../assets/Images/Buzos/HOODIE CROP GASTHETICA (EXPERIMENTAL) BACK - .png'],
    cuidados: 'Lavar a máquina en ciclo delicado.',
    talles: ['S', 'M', 'L'],
    precio: 25000,
    stock: 'stock',
    destacada: true,
  },
  {
    id: 13,
    tipo: 'Buzo',
    nombre: 'Hoodie LongsLeeve',
    descripcion:
      'Una remera con un estampado original y llamativo que refleja tu personalidad única.',
      genero:'Hombre',
      imgUrl: ['../../assets/Images/Buzos/LONGSLEEVE GASTHETICA FRONT - .png','../../assets/Images/Buzos/LONGSLEEVE GASTHETICA BACK - .png','../../assets/Images/Buzos/LONGSLEEVE GASTHETICA FRONT - .png','../../assets/Images/Buzos/LONGSLEEVE GASTHETICA BACK - .png'],
    cuidados: 'Lavar a máquina en ciclo delicado.',
    talles: ['S', 'M', 'L'],
    precio: 25000,
    stock: 'stock',
    destacada: true,
  },
  {
    id: 14,
    tipo: 'Buzo',
    nombre: 'Oversized Hoodie',
    descripcion:
      'Un buzo con un estampado original y llamativo que refleja tu personalidad única.',
      genero:'Hombre',
      imgUrl: ['../../assets/Images/Buzos/OVERSIZED HOODIE GASTHETICA FRONT - .png','../../assets/Images/Buzos/OVERSIZED HOODIE GASTHETICA BACK - .png','../../assets/Images/Buzos/OVERSIZED HOODIE GASTHETICA FRONT - .png','../../assets/Images/Buzos/OVERSIZED HOODIE GASTHETICA BACK - .png'],
    cuidados: 'Lavar a máquina en ciclo delicado.',
    talles: ['S', 'M', 'L'],
    precio: 25000,
    stock: 'stock',
    destacada: true,
  },
  {
    id: 15,
    tipo: 'Buzo',
    nombre: 'Hoodie Crewneck',
    descripcion:
      'Una remera con un estampado original y llamativo que refleja tu personalidad única.',
      genero:'Hombre',
      imgUrl: ['../../assets/Images/Buzos/VINTAGE CREWNECK GASTHETICA FRONT - .png','../../assets/Images/Buzos/VINTAGE CREWNECK GASTHETICA BACK - .png','../../assets/Images/Buzos/VINTAGE CREWNECK GASTHETICA FRONT - .png','../../assets/Images/Buzos/VINTAGE CREWNECK GASTHETICA BACK - .png'],
    cuidados: 'Lavar a máquina en ciclo delicado.',
    talles: ['S', 'M', 'L'],
    precio: 25000,
    stock: 'stock',
    destacada: true,
  },
  {
    id: 16,
    tipo: 'Buzo',
    nombre: 'Zip Hoodie',
    descripcion:
      'Una remera con un estampado original y llamativo que refleja tu personalidad única.',
      genero:'Hombre',
      imgUrl: ['../../assets/Images/Buzos/ZIP HOODIE GASTHETICA FRONT - .png','../../assets/Images/Buzos/ZIP HOODIE GASTHETICA BACK - .png','../../assets/Images/Buzos/ZIP HOODIE GASTHETICA FRONT - .png','../../assets/Images/Buzos/ZIP HOODIE GASTHETICA BACK - .png'],
    cuidados: 'Lavar a máquina en ciclo delicado.',
    talles: ['S', 'M', 'L'],
    precio: 25000,
    stock: 'stock',
    destacada: true,
  },
  {
    id: 17,
    tipo: 'Pantalon',
    nombre: 'ShortPant',
    descripcion:
      'Una remera con un estampado original y llamativo que refleja tu personalidad única.',
      genero:'Hombre',
      imgUrl: ['../../assets/Images/Pantalones/SHORTPANTS GASTHETICA FRONT - .png','../../assets/Images/Pantalones/SHORTPANTS GASTHETICA BACK - .png','../../assets/Images/Pantalones/SHORTPANTS GASTHETICA FRONT - .png','../../assets/Images/Pantalones/SHORTPANTS GASTHETICA BACK - .png'],
    cuidados: 'Lavar a máquina en ciclo delicado.',
    talles: ['S', 'M', 'L'],
    precio: 25000,
    stock: 'stock',
    destacada: true,
  },
  {
    id: 18,
    tipo: 'Remera',
    nombre: 'Boxy Tee2',
    descripcion:
      'Una cálida bufanda de lana para mantenerte abrigado durante los días fríos de invierno.',
      genero:'Unisex',
      imgUrl: ['../../assets/Images/Remeras/BOXY TEE GASTHETICA (BASIC) FRONT - .png','../../assets/Images/Remeras/BOXY TEE GASTHETICA (BASIC) BACK - .png','../../assets/Images/Remeras/BOXY TEE GASTHETICA (BASIC) FRONT - .png','../../assets/Images/Remeras/BOXY TEE GASTHETICA (BASIC) BACK - .png'],
    cuidados: 'Lavar a mano con detergente suave y secar al aire.',
    talles: ['Único'],
    precio: 15000,
    stock: 'stock',
    destacada: false,
  },
  {
    id: 19,
    tipo: 'Remera',
    nombre: 'Remera Open Collar',
    descripcion:
      'Una cálida bufanda de lana para mantenerte abrigado durante los días fríos de invierno.',
      genero:'Unisex',
      imgUrl: ['../../assets/Images/Remeras/SHIRT OPEN COLLAR GASTHETICA FRONT - .png','../../assets/Images/Remeras/SHIRT OPEN COLLAR GASTHETICA BACK - .png','../../assets/Images/Remeras/SHIRT OPEN COLLAR GASTHETICA FRONT - .png','../../assets/Images/Remeras/SHIRT OPEN COLLAR GASTHETICA BACK - .png'],
    cuidados: 'Lavar a mano con detergente suave y secar al aire.',
    talles: ['Único'],
    precio: 15000,
    stock: 'stock',
    destacada: false,
  },
];
